### ISSUE TITLE
YAML support for Home Assistant style configuration files

### ISSUE THREAD

**Issue by ThomDietrich** [samuelcolvin/jinjahtml-vscode#49]
Hello there!
Thanks for this nice extension. It would be amazing if it could be used in combination with Home Assistant configuration files. However, the way jinja is applied inside these files seems not supported. 

For reference: 
* https://www.home-assistant.io
* https://www.home-assistant.io/docs/configuration/templating/#building-templates
* https://www.home-assistant.io/integrations/template/#examples

To illustrate the issue I've composed a MWE below (not a HA MWE but sufficient for the issue). You'll see that neither the code block in the first example nor the inline code in the second example are highlighted. 

Would it be possible to extend the extension logic to cover Home Assistant configs?

```yaml
sensors:
  washingmachine_opstate:
    value_template: >-
      {% set power = states('sensor.washingmachine_power') | float %}
      {% if power <= 1.0 %}
        Standby
      {% else %}
        Active
      {% endif %}

automation:
  - alias: washingmachine_finished
    trigger:
      platform: state
      entity_id: sensor.washingmachine_opstate
      from: 'Active'
      to: 'Standby'
    action:
      service: system_log.write
      data_template:
        message: "washingmachine_opstate changed {{ states('sensor.washingmachine_opstate') }}"
```

![grafik](https://user-images.githubusercontent.com/2870104/76788635-92f07980-67bb-11ea-93ba-10435c6c8b20.png)
